#全局配置文件
#主要作用是对一些默认的配置进行修改
server:
  port: 8080  #将Tomcat默认端口设置为8080
mybatis:
  mapper-locations: classpath:mapping/*.xml  #制定mybatis中的动态sql代码存放路径和文件，这里是mapping文件夹下
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    username: root
    password: 12345678  #改下密码（数据库密码）
    url: jdbc:mysql://47.96.126.229/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #l47.96.126.229是服务器ip，mall是数据集名称