server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    username: root
    password: 123456  #改下密码
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC #localhost改成服务器ip